


'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Partial Public NotInheritable Class Application
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.DataWorkspace)

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(ByVal applicationDefinition As Global.Microsoft.LightSwitch.Model.IApplicationDefinition)
            MyBase.New(applicationDefinition)

            Global.LightSwitchApplication.Application.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Application_Initialize()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Application_LoggedIn()
        End Sub
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Shared Shadows ReadOnly Property Current As Global.LightSwitchApplication.Application
            Get
                Return DirectCast(Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Current, Global.LightSwitchApplication.Application)
            End Get
        End Property

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Home_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Home_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowHome screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowHome()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowHome)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SearchAppointments_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SearchAppointments_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowSearchAppointments screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowSearchAppointments()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowSearchAppointments)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SearchCustomers_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SearchCustomers_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowSearchCustomers screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowSearchCustomers()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowSearchCustomers)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SearchEmployees_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SearchEmployees_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowSearchEmployees screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowSearchEmployees()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowSearchEmployees)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDetail_CanRun(ByRef result As Boolean, ByVal CustomerId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDetail_Run(ByRef handled As Boolean, ByVal CustomerId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowCustomerDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCustomerDetail(ByVal CustomerId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCustomerDetail, CustomerId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeDetail_CanRun(ByRef result As Boolean, ByVal EmployeeId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeDetail_Run(ByRef handled As Boolean, ByVal EmployeeId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEmployeeDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEmployeeDetail(ByVal EmployeeId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEmployeeDetail, EmployeeId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewAppointment_CanRun(ByRef result As Boolean, ByVal CustomerID As Global.System.Nullable(Of Integer))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewAppointment_Run(ByRef handled As Boolean, ByVal CustomerID As Global.System.Nullable(Of Integer))
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowCreateNewAppointment screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCreateNewAppointment(ByVal CustomerID As Global.System.Nullable(Of Integer))
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCreateNewAppointment, CustomerID)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewCustomer_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewCustomer_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowCreateNewCustomer screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCreateNewCustomer()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCreateNewCustomer)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEmployee_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEmployee_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowCreateNewEmployee screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCreateNewEmployee()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCreateNewEmployee)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateSampleData_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateSampleData_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowCreateSampleData screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCreateSampleData()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCreateSampleData)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AppointmentDetail_CanRun(ByRef result As Boolean, ByVal AppointmentId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AppointmentDetail_Run(ByRef handled As Boolean, ByVal AppointmentId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowAppointmentDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowAppointmentDetail(ByVal AppointmentId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowAppointmentDetail, AppointmentId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RoomDetail_CanRun(ByRef result As Boolean, ByVal RoomId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RoomDetail_Run(ByRef handled As Boolean, ByVal RoomId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowRoomDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowRoomDetail(ByVal RoomId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowRoomDetail, RoomId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.Application.DetailsClass.PropertySet, Global.LightSwitchApplication.Application.DetailsClass.CommandSet, Global.LightSwitchApplication.Application.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializeCommandEntry = Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowHome
                Dim initializeMethodEntry = Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowHome
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ApplicationEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_Initialized, _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_LoggedIn)
            Private Shared Sub __Application_Initialized(a As Global.LightSwitchApplication.Application)
                a.Application_Initialize()
            End Sub
            Private Shared Sub __Application_LoggedIn(a As Global.LightSwitchApplication.Application)
                a.Application_LoggedIn()
            End Sub

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As Global.LightSwitchApplication.Application.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As Global.LightSwitchApplication.Application.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As Global.LightSwitchApplication.Application.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Protected Overrides Function CreateScreen(ByVal screenName As String, ByVal ParamArray args() As Object) As Global.Microsoft.LightSwitch.Client.IScreenObject
                Select Case screenName
                    Case "Home"
                        Return Global.LightSwitchApplication.Home.CreateInstance()
                    Case "SearchAppointments"
                        Return Global.LightSwitchApplication.SearchAppointments.CreateInstance()
                    Case "SearchCustomers"
                        Return Global.LightSwitchApplication.SearchCustomers.CreateInstance()
                    Case "SearchEmployees"
                        Return Global.LightSwitchApplication.SearchEmployees.CreateInstance()
                    Case "CustomerDetail"
                        Return Global.LightSwitchApplication.CustomerDetail.CreateInstance(CType(args(0), Integer))
                    Case "EmployeeDetail"
                        Return Global.LightSwitchApplication.EmployeeDetail.CreateInstance(CType(args(0), Integer))
                    Case "CreateNewAppointment"
                        Return Global.LightSwitchApplication.CreateNewAppointment.CreateInstance(CType(args(0), Global.System.Nullable(Of Integer)))
                    Case "CreateNewCustomer"
                        Return Global.LightSwitchApplication.CreateNewCustomer.CreateInstance()
                    Case "CreateNewEmployee"
                        Return Global.LightSwitchApplication.CreateNewEmployee.CreateInstance()
                    Case "CreateSampleData"
                        Return Global.LightSwitchApplication.CreateSampleData.CreateInstance()
                    Case "AppointmentDetail"
                        Return Global.LightSwitchApplication.AppointmentDetail.CreateInstance(CType(args(0), Integer))
                    Case "RoomDetail"
                        Return Global.LightSwitchApplication.RoomDetail.CreateInstance(CType(args(0), Integer))
                End Select
            
                Return MyBase.CreateScreen(screenName, args)
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationPropertySet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationCommandSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowHome As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowHome), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSearchAppointments As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowSearchAppointments), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSearchCustomers As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowSearchCustomers), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSearchEmployees As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowSearchEmployees), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewAppointment As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowCreateNewAppointment), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewCustomer As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowCreateNewCustomer), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewEmployee As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowCreateNewEmployee), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateSampleData As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowCreateSampleData), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationMethodSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowHome As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowHome), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSearchAppointments As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowSearchAppointments), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSearchCustomers As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowSearchCustomers), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSearchEmployees As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowSearchEmployees), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCustomerDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCustomerDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEmployeeDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEmployeeDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewAppointment As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCreateNewAppointment), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewCustomer As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCreateNewCustomer), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewEmployee As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCreateNewEmployee), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateSampleData As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCreateSampleData), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowAppointmentDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowAppointmentDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowRoomDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowRoomDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties

                Public Shared ReadOnly ShowHome As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowHome",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowHome_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowHome_CreateExecutableObject)
                Private Shared Sub _ShowHome_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowHomeCommand, sf)
                End Sub
                Private Shared Function _ShowHome_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowHome.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowSearchAppointments As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSearchAppointments",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSearchAppointments_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSearchAppointments_CreateExecutableObject)
                Private Shared Sub _ShowSearchAppointments_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSearchAppointmentsCommand, sf)
                End Sub
                Private Shared Function _ShowSearchAppointments_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowSearchAppointments.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowSearchCustomers As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSearchCustomers",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSearchCustomers_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSearchCustomers_CreateExecutableObject)
                Private Shared Sub _ShowSearchCustomers_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSearchCustomersCommand, sf)
                End Sub
                Private Shared Function _ShowSearchCustomers_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowSearchCustomers.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowSearchEmployees As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSearchEmployees",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSearchEmployees_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSearchEmployees_CreateExecutableObject)
                Private Shared Sub _ShowSearchEmployees_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSearchEmployeesCommand, sf)
                End Sub
                Private Shared Function _ShowSearchEmployees_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowSearchEmployees.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowCreateNewAppointment As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewAppointment",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewAppointment_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewAppointment_CreateExecutableObject)
                Private Shared Sub _ShowCreateNewAppointment_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewAppointmentCommand, sf)
                End Sub
                Private Shared Function _ShowCreateNewAppointment_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowCreateNewAppointment.CreateInvocation(New Object(1 - 1) { })
                End Function

                Public Shared ReadOnly ShowCreateNewCustomer As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewCustomer",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewCustomer_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewCustomer_CreateExecutableObject)
                Private Shared Sub _ShowCreateNewCustomer_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewCustomerCommand, sf)
                End Sub
                Private Shared Function _ShowCreateNewCustomer_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowCreateNewCustomer.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowCreateNewEmployee As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewEmployee",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewEmployee_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewEmployee_CreateExecutableObject)
                Private Shared Sub _ShowCreateNewEmployee_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewEmployeeCommand, sf)
                End Sub
                Private Shared Function _ShowCreateNewEmployee_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowCreateNewEmployee.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowCreateSampleData As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateSampleData",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateSampleData_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateSampleData_CreateExecutableObject)
                Private Shared Sub _ShowCreateSampleData_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateSampleDataCommand, sf)
                End Sub
                Private Shared Function _ShowCreateSampleData_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowCreateSampleData.CreateInvocation(New Object(0 - 1) { })
                End Function

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties

                Public Shared ReadOnly ShowHome As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowHome",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowHome_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowHome_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowHome_InvokeMethod)
                Private Shared Sub _ShowHome_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowHomeMethod, sf)
                End Sub
                Private Shared Function _ShowHome_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.Home_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowHome_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.Home_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:Home", Function() Global.LightSwitchApplication.Home.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowSearchAppointments As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSearchAppointments",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchAppointments_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchAppointments_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchAppointments_InvokeMethod)
                Private Shared Sub _ShowSearchAppointments_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSearchAppointmentsMethod, sf)
                End Sub
                Private Shared Function _ShowSearchAppointments_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.SearchAppointments_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowSearchAppointments_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.SearchAppointments_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:SearchAppointments", Function() Global.LightSwitchApplication.SearchAppointments.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowSearchCustomers As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSearchCustomers",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchCustomers_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchCustomers_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchCustomers_InvokeMethod)
                Private Shared Sub _ShowSearchCustomers_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSearchCustomersMethod, sf)
                End Sub
                Private Shared Function _ShowSearchCustomers_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.SearchCustomers_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowSearchCustomers_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.SearchCustomers_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:SearchCustomers", Function() Global.LightSwitchApplication.SearchCustomers.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowSearchEmployees As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSearchEmployees",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchEmployees_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchEmployees_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSearchEmployees_InvokeMethod)
                Private Shared Sub _ShowSearchEmployees_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSearchEmployeesMethod, sf)
                End Sub
                Private Shared Function _ShowSearchEmployees_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.SearchEmployees_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowSearchEmployees_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.SearchEmployees_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:SearchEmployees", Function() Global.LightSwitchApplication.SearchEmployees.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCustomerDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCustomerDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCustomerDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCustomerDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCustomerDetail_InvokeMethod)
                Private Shared Sub _ShowCustomerDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCustomerDetailMethod, sf)
                End Sub
                Private Shared Function _ShowCustomerDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CustomerDetail_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCustomerDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CustomerDetail_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:CustomerDetail", Function() Global.LightSwitchApplication.CustomerDetail.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEmployeeDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEmployeeDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEmployeeDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEmployeeDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEmployeeDetail_InvokeMethod)
                Private Shared Sub _ShowEmployeeDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEmployeeDetailMethod, sf)
                End Sub
                Private Shared Function _ShowEmployeeDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EmployeeDetail_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEmployeeDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EmployeeDetail_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:EmployeeDetail", Function() Global.LightSwitchApplication.EmployeeDetail.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCreateNewAppointment As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewAppointment",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewAppointment_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewAppointment_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewAppointment_InvokeMethod)
                Private Shared Sub _ShowCreateNewAppointment_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewAppointmentMethod, sf)
                End Sub
                Private Shared Function _ShowCreateNewAppointment_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CreateNewAppointment_CanRun(result, CType(args(0), Global.System.Nullable(Of Integer)))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCreateNewAppointment_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CreateNewAppointment_Run(handled, CType(args(0), Global.System.Nullable(Of Integer)))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:CreateNewAppointment", Function() Global.LightSwitchApplication.CreateNewAppointment.CreateInstance(CType(args(0), Global.System.Nullable(Of Integer))), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCreateNewCustomer As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewCustomer",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewCustomer_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewCustomer_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewCustomer_InvokeMethod)
                Private Shared Sub _ShowCreateNewCustomer_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewCustomerMethod, sf)
                End Sub
                Private Shared Function _ShowCreateNewCustomer_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CreateNewCustomer_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCreateNewCustomer_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CreateNewCustomer_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:CreateNewCustomer", Function() Global.LightSwitchApplication.CreateNewCustomer.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCreateNewEmployee As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewEmployee",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewEmployee_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewEmployee_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewEmployee_InvokeMethod)
                Private Shared Sub _ShowCreateNewEmployee_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewEmployeeMethod, sf)
                End Sub
                Private Shared Function _ShowCreateNewEmployee_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CreateNewEmployee_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCreateNewEmployee_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CreateNewEmployee_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:CreateNewEmployee", Function() Global.LightSwitchApplication.CreateNewEmployee.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCreateSampleData As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateSampleData",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateSampleData_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateSampleData_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateSampleData_InvokeMethod)
                Private Shared Sub _ShowCreateSampleData_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateSampleDataMethod, sf)
                End Sub
                Private Shared Function _ShowCreateSampleData_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CreateSampleData_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCreateSampleData_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CreateSampleData_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:CreateSampleData", Function() Global.LightSwitchApplication.CreateSampleData.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowAppointmentDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowAppointmentDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowAppointmentDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowAppointmentDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowAppointmentDetail_InvokeMethod)
                Private Shared Sub _ShowAppointmentDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowAppointmentDetailMethod, sf)
                End Sub
                Private Shared Function _ShowAppointmentDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.AppointmentDetail_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowAppointmentDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.AppointmentDetail_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:AppointmentDetail", Function() Global.LightSwitchApplication.AppointmentDetail.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowRoomDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowRoomDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowRoomDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowRoomDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowRoomDetail_InvokeMethod)
                Private Shared Sub _ShowRoomDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowRoomDetailMethod, sf)
                End Sub
                Private Shared Function _ShowRoomDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.RoomDetail_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowRoomDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.RoomDetail_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:RoomDetail", Function() Global.LightSwitchApplication.RoomDetail.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
            End Class

            Private _ShowHomeMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSearchAppointmentsMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSearchCustomersMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSearchEmployeesMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCustomerDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEmployeeDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewAppointmentMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewCustomerMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewEmployeeMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateSampleDataMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowAppointmentDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowRoomDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowHomeCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSearchAppointmentsCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSearchCustomersCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSearchEmployeesCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewAppointmentCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewCustomerCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewEmployeeCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateSampleDataCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

        End Class

    End Class

End Namespace
Namespace LightSwitchApplication
    <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> 
    <Global.System.Diagnostics.DebuggerNonUserCode> 
    <Global.System.CodeDom.Compiler.GeneratedCode("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")>
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader))> 
    <Global.Microsoft.LightSwitch.Model.ModuleDefinitionLoader("LightSwitchApplication")>
    Public Class ClientModuleLoader
        Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader

        Public Function GetModelResourceManager() As Global.System.Resources.ResourceManager Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader.GetModelResourceManager
            Return Nothing
        End Function

        Public Function LoadModelFragments() As Global.System.Collections.Generic.IEnumerable(Of Global.System.IO.Stream) Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader.LoadModelFragments
            Dim assembly As Global.System.Reflection.Assembly = Global.System.Reflection.Assembly.GetExecutingAssembly
            Dim streams As New Global.System.Collections.Generic.List(Of Global.System.IO.Stream)

            For Each resourceName as Global.System.String In assembly.GetManifestResourceNames
                If resourceName.EndsWith(".lsml", Global.System.StringComparison.OrdinalIgnoreCase) Then
                    streams.Add(assembly.GetManifestResourceStream(resourceName))
                End If
            Next

            Return streams
        End Function
    End Class
End Namespace
