//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Cloud.Integration.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlCommandResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlCommandResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Cloud.Integration.Common.Properties.SqlCommandResources", typeof(SqlCommandResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SqlAzurePersistenceQueue_DequeueXmlData.
        /// </summary>
        internal static string SqlAzurePersistenceQueueDequeueXmlData {
            get {
                return ResourceManager.GetString("SqlAzurePersistenceQueueDequeueXmlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SqlAzurePersistenceQueue_Enqueue.
        /// </summary>
        internal static string SqlAzurePersistenceQueueEnqueue {
            get {
                return ResourceManager.GetString("SqlAzurePersistenceQueueEnqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SqlAzurePersistenceQueue_New.
        /// </summary>
        internal static string SqlAzurePersistenceQueueNew {
            get {
                return ResourceManager.GetString("SqlAzurePersistenceQueueNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SqlAzurePersistenceQueue_QueryXmlData.
        /// </summary>
        internal static string SqlAzurePersistenceQueueQueryXmlData {
            get {
                return ResourceManager.GetString("SqlAzurePersistenceQueueQueryXmlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_SqlAzurePersistenceQueue_Remove.
        /// </summary>
        internal static string SqlAzurePersistenceQueueRemove {
            get {
                return ResourceManager.GetString("SqlAzurePersistenceQueueRemove", resourceCulture);
            }
        }
    }
}
