<?xml version="1.0" encoding="utf-8"?><Database Name="Server" Class="IdRangesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLFULL;Initial Catalog=Server;Integrated Security=True" SettingsObjectName="Services.Properties.Settings" SettingsPropertyName="Server" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IdRanges" Member="IdRanges">
    <Type Name="IdRange">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Machine" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Min" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Max" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>