'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DataEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DataEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property StateLookups() As DbSet(Of StateLookup)
    Public Overridable Property FirstNames() As DbSet(Of FirstName)
    Public Overridable Property LastNames() As DbSet(Of LastName)

End Class
