'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Services"
    
    ''' <summary>
    ''' Provides members to query and update data in the ApplicationData datasource.
    ''' </summary>
    Public NotInheritable Partial Class ApplicationDataService
        Inherits Global.LightSwitchApplication.ApplicationData
    
        #Region "Constructors"
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Server Interceptions Points"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Inserting(ByVal entity As Global.LightSwitchApplication.Customer)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Inserted(ByVal entity As Global.LightSwitchApplication.Customer)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Updating(ByVal entity As Global.LightSwitchApplication.Customer)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Updated(ByVal entity As Global.LightSwitchApplication.Customer)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Deleting(ByVal entity As Global.LightSwitchApplication.Customer)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Deleted(ByVal entity As Global.LightSwitchApplication.Customer)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Validate(ByVal entity As Global.LightSwitchApplication.Customer, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Customers_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Customer, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Inserting(ByVal entity As Global.LightSwitchApplication.State)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Inserted(ByVal entity As Global.LightSwitchApplication.State)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Updating(ByVal entity As Global.LightSwitchApplication.State)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Updated(ByVal entity As Global.LightSwitchApplication.State)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Deleting(ByVal entity As Global.LightSwitchApplication.State)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Deleted(ByVal entity As Global.LightSwitchApplication.State)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Validate(ByVal entity As Global.LightSwitchApplication.State, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub States_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.State, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Inserting(ByVal entity As Global.LightSwitchApplication.Appointment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Inserted(ByVal entity As Global.LightSwitchApplication.Appointment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Updating(ByVal entity As Global.LightSwitchApplication.Appointment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Updated(ByVal entity As Global.LightSwitchApplication.Appointment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Deleting(ByVal entity As Global.LightSwitchApplication.Appointment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Deleted(ByVal entity As Global.LightSwitchApplication.Appointment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Validate(ByVal entity As Global.LightSwitchApplication.Appointment, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Appointments_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Appointment, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Inserting(ByVal entity As Global.LightSwitchApplication.Employee)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Inserted(ByVal entity As Global.LightSwitchApplication.Employee)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Updating(ByVal entity As Global.LightSwitchApplication.Employee)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Updated(ByVal entity As Global.LightSwitchApplication.Employee)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Deleting(ByVal entity As Global.LightSwitchApplication.Employee)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Deleted(ByVal entity As Global.LightSwitchApplication.Employee)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Validate(ByVal entity As Global.LightSwitchApplication.Employee, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Employees_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Employee, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Inserting(ByVal entity As Global.LightSwitchApplication.Photo)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Inserted(ByVal entity As Global.LightSwitchApplication.Photo)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Updating(ByVal entity As Global.LightSwitchApplication.Photo)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Updated(ByVal entity As Global.LightSwitchApplication.Photo)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Deleting(ByVal entity As Global.LightSwitchApplication.Photo)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Deleted(ByVal entity As Global.LightSwitchApplication.Photo)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Validate(ByVal entity As Global.LightSwitchApplication.Photo, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Photos_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Photo, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Inserting(ByVal entity As Global.LightSwitchApplication.Room)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Inserted(ByVal entity As Global.LightSwitchApplication.Room)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Updating(ByVal entity As Global.LightSwitchApplication.Room)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Updated(ByVal entity As Global.LightSwitchApplication.Room)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Deleting(ByVal entity As Global.LightSwitchApplication.Room)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Deleted(ByVal entity As Global.LightSwitchApplication.Room)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Validate(ByVal entity As Global.LightSwitchApplication.Room, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Rooms_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Room, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Inserting(ByVal entity As Global.LightSwitchApplication.InventoryItem)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Inserted(ByVal entity As Global.LightSwitchApplication.InventoryItem)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Updating(ByVal entity As Global.LightSwitchApplication.InventoryItem)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Updated(ByVal entity As Global.LightSwitchApplication.InventoryItem)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Deleting(ByVal entity As Global.LightSwitchApplication.InventoryItem)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Deleted(ByVal entity As Global.LightSwitchApplication.InventoryItem)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Validate(ByVal entity As Global.LightSwitchApplication.InventoryItem, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub InventoryItems_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.InventoryItem, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executed()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub AvailableEmployees_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub AvailableEmployees_Executing(ByVal StartTime As Global.System.Nullable(Of Date), ByVal EndTime As Global.System.Nullable(Of Date))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub AvailableEmployees_PreprocessQuery(ByVal StartTime As Global.System.Nullable(Of Date), ByVal EndTime As Global.System.Nullable(Of Date), ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Employee))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub AvailableEmployees_Executed(ByVal StartTime As Global.System.Nullable(Of Date), ByVal EndTime As Global.System.Nullable(Of Date), ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Employee))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub AvailableEmployees_ExecuteFailed(ByVal StartTime As Global.System.Nullable(Of Date), ByVal EndTime As Global.System.Nullable(Of Date), ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub UpcomingAppointments_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub UpcomingAppointments_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub UpcomingAppointments_PreprocessQuery(ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Appointment))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub UpcomingAppointments_Executed(ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Appointment))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub UpcomingAppointments_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub UpcomingAppointmentsForAllEmployees_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub UpcomingAppointmentsForAllEmployees_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub UpcomingAppointmentsForAllEmployees_PreprocessQuery(ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Appointment))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub UpcomingAppointmentsForAllEmployees_Executed(ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Appointment))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub UpcomingAppointmentsForAllEmployees_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_Executing(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutingDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_Executed(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutedDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_ExecuteFailed(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecuteFailedDescriptor)
        End Sub
    
        #End Region
        
        #Region "Details Class"
    
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        Public MustInherit Shadows Class DetailsClass
         
            Shared Sub New()
            End Sub
    
            Private Sub New()
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __CustomersEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Customer) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Customer)( _
                    "Customers",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Filter)
            Private Shared Function __Customers_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Customers_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Customers_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Customers_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Customers_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Customers_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Customers_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Customers_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Customers_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer)
                d.Customers_Inserting(e)
            End Sub
            Private Shared Sub __Customers_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer)
                d.Customers_Inserted(e)
            End Sub
            Private Shared Sub __Customers_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer)
                d.Customers_Updating(e)
            End Sub
            Private Shared Sub __Customers_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer)
                d.Customers_Updated(e)
            End Sub
            Private Shared Sub __Customers_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer)
                d.Customers_Deleting(e)
            End Sub
            Private Shared Sub __Customers_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer)
                d.Customers_Deleted(e)
            End Sub
            Private Shared Sub __Customers_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Customer, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Customers_Validate(e, r)
            End Sub
            Private Shared Function __Customers_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Customer, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Customer, Boolean)) = Nothing
                d.Customers_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __StatesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.State) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.State)( _
                    "States",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__States_Filter)
            Private Shared Function __States_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.States_CanInsert(result)
                Return result
            End Function
            Private Shared Function __States_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.States_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __States_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.States_CanDelete(result)
                Return result
            End Function
            Private Shared Function __States_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.States_CanRead(result)
                Return result
            End Function
            Private Shared Sub __States_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State)
                d.States_Inserting(e)
            End Sub
            Private Shared Sub __States_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State)
                d.States_Inserted(e)
            End Sub
            Private Shared Sub __States_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State)
                d.States_Updating(e)
            End Sub
            Private Shared Sub __States_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State)
                d.States_Updated(e)
            End Sub
            Private Shared Sub __States_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State)
                d.States_Deleting(e)
            End Sub
            Private Shared Sub __States_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State)
                d.States_Deleted(e)
            End Sub
            Private Shared Sub __States_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.State, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.States_Validate(e, r)
            End Sub
            Private Shared Function __States_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.State, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.State, Boolean)) = Nothing
                d.States_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __AppointmentsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Appointment) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Appointment)( _
                    "Appointments",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Appointments_Filter)
            Private Shared Function __Appointments_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Appointments_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Appointments_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Appointments_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Appointments_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Appointments_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Appointments_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Appointments_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Appointments_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment)
                d.Appointments_Inserting(e)
            End Sub
            Private Shared Sub __Appointments_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment)
                d.Appointments_Inserted(e)
            End Sub
            Private Shared Sub __Appointments_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment)
                d.Appointments_Updating(e)
            End Sub
            Private Shared Sub __Appointments_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment)
                d.Appointments_Updated(e)
            End Sub
            Private Shared Sub __Appointments_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment)
                d.Appointments_Deleting(e)
            End Sub
            Private Shared Sub __Appointments_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment)
                d.Appointments_Deleted(e)
            End Sub
            Private Shared Sub __Appointments_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Appointment, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Appointments_Validate(e, r)
            End Sub
            Private Shared Function __Appointments_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Appointment, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Appointment, Boolean)) = Nothing
                d.Appointments_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __EmployeesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Employee) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Employee)( _
                    "Employees",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Employees_Filter)
            Private Shared Function __Employees_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Employees_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Employees_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Employees_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Employees_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Employees_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Employees_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Employees_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Employees_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee)
                d.Employees_Inserting(e)
            End Sub
            Private Shared Sub __Employees_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee)
                d.Employees_Inserted(e)
            End Sub
            Private Shared Sub __Employees_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee)
                d.Employees_Updating(e)
            End Sub
            Private Shared Sub __Employees_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee)
                d.Employees_Updated(e)
            End Sub
            Private Shared Sub __Employees_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee)
                d.Employees_Deleting(e)
            End Sub
            Private Shared Sub __Employees_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee)
                d.Employees_Deleted(e)
            End Sub
            Private Shared Sub __Employees_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Employee, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Employees_Validate(e, r)
            End Sub
            Private Shared Function __Employees_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Employee, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Employee, Boolean)) = Nothing
                d.Employees_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __PhotosEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Photo) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Photo)( _
                    "Photos",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Photos_Filter)
            Private Shared Function __Photos_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Photos_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Photos_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Photos_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Photos_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Photos_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Photos_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Photos_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Photos_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo)
                d.Photos_Inserting(e)
            End Sub
            Private Shared Sub __Photos_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo)
                d.Photos_Inserted(e)
            End Sub
            Private Shared Sub __Photos_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo)
                d.Photos_Updating(e)
            End Sub
            Private Shared Sub __Photos_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo)
                d.Photos_Updated(e)
            End Sub
            Private Shared Sub __Photos_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo)
                d.Photos_Deleting(e)
            End Sub
            Private Shared Sub __Photos_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo)
                d.Photos_Deleted(e)
            End Sub
            Private Shared Sub __Photos_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Photo, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Photos_Validate(e, r)
            End Sub
            Private Shared Function __Photos_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Photo, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Photo, Boolean)) = Nothing
                d.Photos_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __RoomsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Room) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Room)( _
                    "Rooms",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Rooms_Filter)
            Private Shared Function __Rooms_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Rooms_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Rooms_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Rooms_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Rooms_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Rooms_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Rooms_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.Rooms_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Rooms_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room)
                d.Rooms_Inserting(e)
            End Sub
            Private Shared Sub __Rooms_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room)
                d.Rooms_Inserted(e)
            End Sub
            Private Shared Sub __Rooms_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room)
                d.Rooms_Updating(e)
            End Sub
            Private Shared Sub __Rooms_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room)
                d.Rooms_Updated(e)
            End Sub
            Private Shared Sub __Rooms_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room)
                d.Rooms_Deleting(e)
            End Sub
            Private Shared Sub __Rooms_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room)
                d.Rooms_Deleted(e)
            End Sub
            Private Shared Sub __Rooms_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.Room, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Rooms_Validate(e, r)
            End Sub
            Private Shared Function __Rooms_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Room, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Room, Boolean)) = Nothing
                d.Rooms_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __InventoryItemsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.InventoryItem) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.InventoryItem)( _
                    "InventoryItems",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_CanInsert, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_CanDelete, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_CanRead, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Inserting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Inserted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Updating, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Updated, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Deleting, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Deleted, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Validate, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__InventoryItems_Filter)
            Private Shared Function __InventoryItems_CanInsert(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.InventoryItems_CanInsert(result)
                Return result
            End Function
            Private Shared Function __InventoryItems_CanUpdate(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.InventoryItems_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __InventoryItems_CanDelete(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.InventoryItems_CanDelete(result)
                Return result
            End Function
            Private Shared Function __InventoryItems_CanRead(d As Global.LightSwitchApplication.ApplicationDataService) As Boolean
                Dim result As Boolean = True
                d.InventoryItems_CanRead(result)
                Return result
            End Function
            Private Shared Sub __InventoryItems_Inserting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem)
                d.InventoryItems_Inserting(e)
            End Sub
            Private Shared Sub __InventoryItems_Inserted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem)
                d.InventoryItems_Inserted(e)
            End Sub
            Private Shared Sub __InventoryItems_Updating(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem)
                d.InventoryItems_Updating(e)
            End Sub
            Private Shared Sub __InventoryItems_Updated(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem)
                d.InventoryItems_Updated(e)
            End Sub
            Private Shared Sub __InventoryItems_Deleting(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem)
                d.InventoryItems_Deleting(e)
            End Sub
            Private Shared Sub __InventoryItems_Deleted(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem)
                d.InventoryItems_Deleted(e)
            End Sub
            Private Shared Sub __InventoryItems_Validate(d As Global.LightSwitchApplication.ApplicationDataService, e As Global.LightSwitchApplication.InventoryItem, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.InventoryItems_Validate(e, r)
            End Sub
            Private Shared Function __InventoryItems_Filter(d As Global.LightSwitchApplication.ApplicationDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.InventoryItem, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.InventoryItem, Boolean)) = Nothing
                d.InventoryItems_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __SaveChangesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.ApplicationDataService) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.ApplicationDataService)( _
                    "SaveChanges",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed)
            Private Shared Function __SaveChanges_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.SaveChanges_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __SaveChanges_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.SaveChanges_Executing()
            End Sub
            Private Shared Sub __SaveChanges_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.SaveChanges_Executed()
            End Sub
            Private Shared Sub __SaveChanges_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.SaveChanges_ExecuteFailed(ex)
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __AvailableEmployeesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Employee) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Employee)( _
                    "AvailableEmployees",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__AvailableEmployees_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__AvailableEmployees_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__AvailableEmployees_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__AvailableEmployees_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__AvailableEmployees_PreprocessQuery)
            Private Shared Function __AvailableEmployees_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.AvailableEmployees_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __AvailableEmployees_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.AvailableEmployees_Executing(DirectCast(args(0), Global.System.Nullable(Of Date)), DirectCast(args(1), Global.System.Nullable(Of Date)))
            End Sub
            Private Shared Sub __AvailableEmployees_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.AvailableEmployees_Executed(DirectCast(args(0), Global.System.Nullable(Of Date)), DirectCast(args(1), Global.System.Nullable(Of Date)), DirectCast(args(2), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Employee)))
            End Sub
            Private Shared Sub __AvailableEmployees_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.AvailableEmployees_ExecuteFailed(DirectCast(args(0), Global.System.Nullable(Of Date)), DirectCast(args(1), Global.System.Nullable(Of Date)), ex)
            End Sub
            Private Shared Function __AvailableEmployees_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Employee) = DirectCast(args(2), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Employee))
                d.AvailableEmployees_PreprocessQuery(DirectCast(args(0), Global.System.Nullable(Of Date)), DirectCast(args(1), Global.System.Nullable(Of Date)), query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __UpcomingAppointmentsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Appointment) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Appointment)( _
                    "UpcomingAppointments",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointments_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointments_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointments_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointments_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointments_PreprocessQuery)
            Private Shared Function __UpcomingAppointments_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.UpcomingAppointments_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __UpcomingAppointments_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.UpcomingAppointments_Executing()
            End Sub
            Private Shared Sub __UpcomingAppointments_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.UpcomingAppointments_Executed(DirectCast(args(0), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Appointment)))
            End Sub
            Private Shared Sub __UpcomingAppointments_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.UpcomingAppointments_ExecuteFailed(ex)
            End Sub
            Private Shared Function __UpcomingAppointments_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Appointment) = DirectCast(args(0), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Appointment))
                d.UpcomingAppointments_PreprocessQuery(query)
                Return query
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __UpcomingAppointmentsForAllEmployeesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Appointment) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.ApplicationDataService, Global.LightSwitchApplication.Appointment)( _
                    "UpcomingAppointmentsForAllEmployees",
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointmentsForAllEmployees_CanExecute, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointmentsForAllEmployees_Executing, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointmentsForAllEmployees_Executed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointmentsForAllEmployees_Failed, _
                    AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__UpcomingAppointmentsForAllEmployees_PreprocessQuery)
            Private Shared Function __UpcomingAppointmentsForAllEmployees_CanExecute(d As Global.LightSwitchApplication.ApplicationDataService, r As Boolean) As Boolean
                d.UpcomingAppointmentsForAllEmployees_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __UpcomingAppointmentsForAllEmployees_Executing(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.UpcomingAppointmentsForAllEmployees_Executing()
            End Sub
            Private Shared Sub __UpcomingAppointmentsForAllEmployees_Executed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object())
                d.UpcomingAppointmentsForAllEmployees_Executed(DirectCast(args(0), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Appointment)))
            End Sub
            Private Shared Sub __UpcomingAppointmentsForAllEmployees_Failed(d As Global.LightSwitchApplication.ApplicationDataService, args As Object(), ex As Global.System.Exception)
                d.UpcomingAppointmentsForAllEmployees_ExecuteFailed(ex)
            End Sub
            Private Shared Function __UpcomingAppointmentsForAllEmployees_PreprocessQuery(d As Global.LightSwitchApplication.ApplicationDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Appointment) = DirectCast(args(0), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Appointment))
                d.UpcomingAppointmentsForAllEmployees_PreprocessQuery(query)
                Return query
            End Function
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Private Shared ReadOnly ___QueryEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryEntry(Of Global.LightSwitchApplication.ApplicationDataService) = _
            New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryEntry(Of Global.LightSwitchApplication.ApplicationDataService)( _
                AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing, _
                AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed, _
                AddressOf Global.LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed)
        Private Shared Sub __Query_Executing(d As Global.LightSwitchApplication.ApplicationDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutingDescriptor)
            d.Query_Executing(queryDescriptor)
        End Sub
        Private Shared Sub __Query_Executed(d As Global.LightSwitchApplication.ApplicationDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutedDescriptor)
            d.Query_Executed(queryDescriptor)
        End Sub
        Private Shared Sub __Query_Failed(d As Global.LightSwitchApplication.ApplicationDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecuteFailedDescriptor)
            d.Query_ExecuteFailed(queryDescriptor)
        End Sub
    
        End Class
    
        #End Region
    
    End Class
    
    #End Region

End Namespace
