-- This script will create the database.
-- If you installed SQL-Server to the default location no changes are required below,
-- but if not you will need to change the path for FILENAME in the initial create below.
-- Run GenerateTablesProceduresAndDataScript.sql after executing this script

USE [master]
GO


CREATE DATABASE [NORTHWND_NEW.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Northwind', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\North\NORTHWND.MDF' , SIZE = 8384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Northwind_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\North\NORTHWND_NEW.MDF_log.ldf' , SIZE = 2560KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NORTHWND_NEW.MDF].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NORTHWND_NEW.MDF] SET  READ_WRITE 
GO


