// <auto-generated />
namespace ContosoUniversity.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddBirthDate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206081812593_AddBirthDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1dzW7kNhK+L7DvIOi0CZBuj3c3mAzaCTz+yRoZj41pb64DWmLbRCSqV2Ib9rPlkEfKKyyp1g//RUpqWc5lxqbIYrHqY7GKrJr58/c/Vj89p0nwBPMCZfgkfLc4CgOIoyxG+OEk3JHNd+/Dn378+99WF3H6HPxa9ztm/ehIXJyEj4RsPyyXRfQIU1AsUhTlWZFtyCLK0iWIs+Xx0dH75bujJaQkQkorCFZfdpigFJa/0F/PMhzBLdmB5DqLYVJU7fTLuqQafAYpLLYggich7Uso/f9iVHJNXhbnp5/C4DRBgDKzhsnGk7OjHxhnYTMnnfWCckde7l62sJyZTbrLC8j3ob1+gS9CA226zbMtzMnLF7gRRl6dh8FSHL2UhzeDlZGMkZPwCpN/HofB512SgPuENmxAQnkKtt9/WJMshz9DDHNAYHwLCIE51dLnDMNKGB+237vJ44fl0TGTxxJgnBFAqLoV1iVG7xBJYM3lmuQUOmFwiZ5h/AniB/LYcHoNnuuWf1P8UBVSoNExJN9BzcLss57lMEak6JKOncg53IKcpBCTbjlLlD6DJ/RQysdIMwy+wKTsUjyi7R6ci/bz172G6RIu8yz9kiXC4Prr1zuQP0BK6y4zdlnTvyMPFi9wniUJI1FoeWy/V1PwLCofFQ7VHr4MXuGCgiKisNYzWJEVurUcql8bBmoWNV3qVfA8rpatKbAaCE7pPYyECENfQ+EDYrOxuIphuagJDAb7c3J78XEX70FaTnsOI5SCJAxuc/pTdfi9D4N1BBhFf0uyJlQH51SizQz05zuU+jN6S4+1DFtUuV++61Y6jVOEEYU5oHrvskhSZ61dEvooG8vYUbe9bHw3xnEMG2rhUjazvbZ/a0fC4CMoYIVtxutenaFV5f9BOeyHnV7i87aesoG3GFhX/m42GxTB06JAD9h4VrYTfFX7txxbuimat/UdBAGFwR7nQLv1fc+ATqPhZHo+ZVFlwMcz"
                       + "zn7Wit9IhwGEjGUX8PQCROsF9YFCO7oPHMTRb8AlcA12Bh6dTlR+zkEM+zgKflCvPevh/rds48weuitva7KLTUa5+vZVCCJa9jSflT2n6zNorzX89jh8WyZGPoK7oqwegpQ1bRN2L0FWAgtO75nfFpEK1LM8y2ZhuD6BgrxKPHOJ8oJco/h1gimUk8eu7aKaQxMM6ZGbRaiUt+IHqAe9yNkFjgMPN7C1Dbyrcb1LCNomKKLMUfuuLN9tksbMtZOoXoo41dFioc5GNxHMGYJBcpax+QDCRN1xCEdoCxL31UskvLYtU14zpfyFhlMQsz3nLqShvDRTSsalS3arJQc2OwaNcbEJG91BcgsM/pZQhMS3FvR1RtdO+B4PdF38TIa4LtG/LbjVwbsDDJQbDheIvZPlsbrB5zCBBAanESl93DNQRKUbLJ/elAsPtjS4rD3aLtQPBaQkGRcE2O5h+8JRksQYbEwARjUCMSndEo60OudiYQ9rZ3lp6ILTqAjvhUQj8y4IML0aeoHQqJmhHEyAP11sZIKJNVBqgdLEiJPYQmsY3G9j9IKhRTiTHc4WWbyBc1lzW25Suu3h0f8AtNL1cvi+lcMww+L30RnLsKDignm9F6PHLGNiJPBZjb7YiDUk8rNDG+hJq1YWKRJozz4dEd6l6SAkBx46cmp01kFUuKpRyPGbuYPQLcy2LGlCoVFfwEjjOYW1RKy34dwIh8tzeWP5RdXN6tqFKVvVL4TmKGoUKdthUToOkjM/eapicwsD/QJBbnkC4C1S6wz9OpUwTE7NzrZKSBu5uMYuw6QihxwctYb3wQLR3Myr8uhwnh3dZ45/wexYpGF2mA8iDO0FtiqOTl/O2ZvzszM2F8xNuD1kontbV0XS5VO4ehXdanX1I4ZYj/pat3Ecmm+r5T6Bs2pYLQ2ZnqtrsN0i/MBlflYtwbpK+/xu7Z/Xme5pLCNBvLKb08xEBQIeoPSVSS2G5W37OSDgHrA9fxanSjcn"
                       + "N6meS/SWVI3VXkHdn/1cj9Hkvy70dqYV4yVdGYN4uUiowEYdGLDcW5CA3PhQe5YluxR3RYtmSlXaKE+manKn0SSBCszUje50xBsXnpj9LoZBWpKwEqIoylSCSBEbTsjhz8fh6DFlLzohyDZ4fHmbKO6fwXhK+xZ3CnWCIE+jbnOnwuUB8oS4ZndabeDLkzKHw6+GxurEGA5ELoT1B6LusX9c8Zootfl7PKW2VUuJSoCaKXbP8CtIdlDMfRK2BCqiHFGXfx+hjK/1Xqqqr9Pekp7kVA+envzNTWfNpeKcFHZVsJ9vNv/Qa24vuW/elObaNAueUtvqTknMm+CplV+8T402E0I4ONrm2Vhp9SJluBXoukhyAFU3iQng1SS+CvBqWmejQ3sM7as9U4qqk95sg7sNsKw1W76rjeJ48ch4aKoSSHkyVdP0OBKDdl34Kd5VuAWa4hh9TGn25diNhFaNujsOVWKj4KB8vKtp9OLP+II1CrrM/MkXMaralfsYuUsDuuZeRrp/WVV3IS7luNLlyL4Ly5fOnlBcXoy8FASmC9Zhsf5fsoY5BdQZXPyLFRHX3a4BRhtYkLvsN4hPwvJb35reJo2zKOJk/oW9iPmPngmYQs0tfgJ59AhyJclzWEltH750tYjddN5smWW5tM4kZE8Z8hm9Y6lWrH5MMwz9+VJKHGP6MxmjxFFCiHvisAIQbcL/xPnqBwGFnGc+FjC4oGdkxMkp4jq0aCtmOooj+9LR13n0pSbF+BbZvTt+P5b5m1eNYZ/zQa4wdEDbAGswtxK8g1iGMdyJMVQrlM3Fg8rmnBVsjzSGOXIj757XUZN7xU2v9PPXzTevMzCmTy6fNpvc+Lg7y9Rx77KZOuVNkwXnULcyAJYjwcJ0K374Wpe3kD7bp5LPGRE2OKgpka9Slzc1Ohxu5GeHEfdqE2eTf6Ajh0/xnTKN3+MIGLl25K9WLeJhW/5SCJraDnkiaHZFHtr3hxlZIiX0UTlxLgh5"
                       + "K1ap62FpjrbJ8eVoRhZqDsia2lr1QtakNkt60mvQJecmy1rV1WdZyrP2z3cnYXyfUb3v7xW8S7c6Krd0c3hUdtWbQZmj/qCjb6irkmmrcYEyi9pFN9+A0rKOyjLdbB6VZ+oGNmCB72JGBd/LpWbtoBVFhhIih5oITSnF/MvMxI3AZ+i5lUw5iqvHwiepTOy3fNMO1+eizbBizBmwxrBDn8Q103qwflqeYrmWuiyXii9DgtNgTZsMvD416yBiqIvKnMSgz6MajIBDicGj2E1NoqL+H/c/H1AvlBmahgRLL8cwEjy/ps8V3mS1CypxVHeRXouuIQExdQtPc4I2ICL0cwSpaWP/QlyVvn6R3sP4Ct/syHZH6JJhep+88MJgjqxt/rKiT+R5dbMt/6HDMZZA2UTshf4Gf9yhJG74vtS8dBlIMA+5em1lumSHKnx4aSjt/48EF0KV+BrH/g6m24QSK27wGjxBM2/dMhQltjpH4CEHaVHRaMfTXyn84vT5x/8DHbTEELtjAAA="; }
        }
    }
}
