//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Cloud.Integration.BizTalk.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Cloud.Integration.BizTalk.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginActivity.
        /// </summary>
        internal static string BeginActivityMethodName {
            get {
                return ResourceManager.GetString("BeginActivityMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteActivity.
        /// </summary>
        internal static string CompleteActivityMethodName {
            get {
                return ResourceManager.GetString("CompleteActivityMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles the trace events received from instrumented distributed applications..
        /// </summary>
        internal static string DiagnosticTraceEventHandlerComponentDesc {
            get {
                return ResourceManager.GetString("DiagnosticTraceEventHandlerComponentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Trace Event Handler.
        /// </summary>
        internal static string DiagnosticTraceEventHandlerComponentName {
            get {
                return ResourceManager.GetString("DiagnosticTraceEventHandlerComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables writing events into standard Win32 debug channel and capture these using the DebugView tool..
        /// </summary>
        internal static string EnableDebugLoggingPropDesc {
            get {
                return ResourceManager.GetString("EnableDebugLoggingPropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Debug Logging.
        /// </summary>
        internal static string EnableDebugLoggingPropName {
            get {
                return ResourceManager.GetString("EnableDebugLoggingPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables writing events into Event Tracing for Windows (ETW)..
        /// </summary>
        internal static string EnableEtwLoggingPropDesc {
            get {
                return ResourceManager.GetString("EnableEtwLoggingPropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ETW Logging.
        /// </summary>
        internal static string EnableEtwLoggingPropName {
            get {
                return ResourceManager.GetString("EnableEtwLoggingPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables to orchestrate multiple components from within Messaging Engine as messages flow through Receive or Send pipelines..
        /// </summary>
        internal static string MessagingRuntimeExtenderComponentDesc {
            get {
                return ResourceManager.GetString("MessagingRuntimeExtenderComponentDesc", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MessagingRuntimeExtenderComponentIcon {
            get {
                object obj = ResourceManager.GetObject("MessagingRuntimeExtenderComponentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging Runtime Extender Component.
        /// </summary>
        internal static string MessagingRuntimeExtenderComponentName {
            get {
                return ResourceManager.GetString("MessagingRuntimeExtenderComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Business Rules policy defining processing steps that extend message handling at runtime..
        /// </summary>
        internal static string MessagingRuntimeExtenderPolicyNamePropDesc {
            get {
                return ResourceManager.GetString("MessagingRuntimeExtenderPolicyNamePropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRE Policy Name.
        /// </summary>
        internal static string MessagingRuntimeExtenderPolicyNamePropName {
            get {
                return ResourceManager.GetString("MessagingRuntimeExtenderPolicyNamePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the Business Rules policy. If not specified, the latest deployed version of the policy will be used..
        /// </summary>
        internal static string MessagingRuntimeExtenderPolicyVersionPropDesc {
            get {
                return ResourceManager.GetString("MessagingRuntimeExtenderPolicyVersionPropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRE Policy Version.
        /// </summary>
        internal static string MessagingRuntimeExtenderPolicyVersionPropName {
            get {
                return ResourceManager.GetString("MessagingRuntimeExtenderPolicyVersionPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables discarding all pass-through traffic so that no events will be published into the Message Box..
        /// </summary>
        internal static string SuppressPassthroughTrafficPropDesc {
            get {
                return ResourceManager.GetString("SuppressPassthroughTrafficPropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Passthrough Traffic.
        /// </summary>
        internal static string SuppressPassthroughTrafficPropName {
            get {
                return ResourceManager.GetString("SuppressPassthroughTrafficPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;Event ID: {1}, Source: {2}, Machine: {3}, Process: {4}, PID: {5}, Thread: {6}, Timestamp: {7}&gt;.
        /// </summary>
        internal static string TraceEventMessageFormatString {
            get {
                return ResourceManager.GetString("TraceEventMessageFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateActivity.
        /// </summary>
        internal static string UpdateActivityMethodName {
            get {
                return ResourceManager.GetString("UpdateActivityMethodName", resourceCulture);
            }
        }
    }
}
