CREATE DATABASE estudo DEFAULT CHARACTER SET utf8;

CREATE TABLE CLIENTE
(
    COD_CLIENTE  		       INT NOT NULL AUTO_INCREMENT,
	CLI_NOME    		       VARCHAR(100) NOT NULL,
    CLI_EMAIL    		       VARCHAR(100) NOT NULL,
    CLI_ENDERECO   		       VARCHAR(100) NOT NULL,
    CLI_BAIRRO   		       VARCHAR(100) NOT NULL,
    CLI_CIDADE   		       VARCHAR(100) NOT NULL,
    CLI_ESTADO                 VARCHAR(2) NOT NULL,   
    PRIMARY KEY (COD_CLIENTE)
);

ALTER TABLE CLIENTE AUTO_INCREMENT = 1000;