<?xml version="1.0" encoding="utf-8"?><Database Name="abc" Class="StudentDataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\abc.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="FP1.Properties.Settings" SettingsPropertyName="abcConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudentInfo" Member="StudentInfos">
    <Type Name="StudentInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Marks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>